tf.random_uniform
tensorflow.python.ops
control_flow_ops
tf.int32
tf.equal
tf.name_scope
tf.image.random_brightness
tf.image.random_saturation
tf.image.random_contrast
tf.image.random_hue
tf.name_scope
tf.shape
tf.image.sample_distorted_bounding_box
tf.constant
tf.image.convert_image_dtype
tf.image.draw_bounding_boxes
tf.expand_dims
tf.summary.image
tf.image.draw_bounding_boxes
tf.image.resize_images
tf.subtract
tf.multiply
tf.image.convert_image_dtype
tf.image.resize_bilinear
tf.squeeze